2023-09-14 11:08:34,429:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-14 11:08:34,431:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-14 11:08:34,431:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-14 11:08:34,431:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-09-14 11:08:35,145:INFO:PyCaret ClassificationExperiment
2023-09-14 11:08:35,145:INFO:Logging name: clf-default-name
2023-09-14 11:08:35,156:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-09-14 11:08:35,156:INFO:version 3.1.0
2023-09-14 11:08:35,156:INFO:Initializing setup()
2023-09-14 11:08:35,156:INFO:self.USI: fa9e
2023-09-14 11:08:35,156:INFO:self._variable_keys: {'USI', 'X_test', 'data', 'html_param', 'fold_shuffle_param', 'target_param', 'y_test', '_available_plots', 'X', '_ml_usecase', 'log_plots_param', 'memory', 'y_train', 'fix_imbalance', 'exp_name_log', 'idx', 'fold_generator', 'y', 'gpu_n_jobs_param', 'logging_param', 'n_jobs_param', 'pipeline', 'seed', 'gpu_param', 'X_train', 'exp_id', 'fold_groups_param', 'is_multiclass'}
2023-09-14 11:08:35,156:INFO:Checking environment
2023-09-14 11:08:35,156:INFO:python_version: 3.10.10
2023-09-14 11:08:35,156:INFO:python_build: ('tags/v3.10.10:aad5f6a', 'Feb  7 2023 17:20:36')
2023-09-14 11:08:35,156:INFO:machine: AMD64
2023-09-14 11:08:35,156:INFO:platform: Windows-10-10.0.22621-SP0
2023-09-14 11:08:35,156:INFO:Memory: svmem(total=16822788096, available=10238922752, percent=39.1, used=6583865344, free=10238922752)
2023-09-14 11:08:35,156:INFO:Physical Core: 8
2023-09-14 11:08:35,156:INFO:Logical Core: 16
2023-09-14 11:08:35,156:INFO:Checking libraries
2023-09-14 11:08:35,156:INFO:System:
2023-09-14 11:08:35,156:INFO:    python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
2023-09-14 11:08:35,156:INFO:executable: c:\Users\asiae\asiae2023\python\venv\Scripts\python.exe
2023-09-14 11:08:35,156:INFO:   machine: Windows-10-10.0.22621-SP0
2023-09-14 11:08:35,156:INFO:PyCaret required dependencies:
2023-09-14 11:08:35,179:INFO:                 pip: 23.2.1
2023-09-14 11:08:35,179:INFO:          setuptools: 68.2.0
2023-09-14 11:08:35,193:INFO:             pycaret: 3.1.0
2023-09-14 11:08:35,193:INFO:             IPython: 8.15.0
2023-09-14 11:08:35,193:INFO:          ipywidgets: 8.1.1
2023-09-14 11:08:35,193:INFO:                tqdm: 4.66.1
2023-09-14 11:08:35,193:INFO:               numpy: 1.23.5
2023-09-14 11:08:35,193:INFO:              pandas: 1.5.3
2023-09-14 11:08:35,193:INFO:              jinja2: 3.1.2
2023-09-14 11:08:35,193:INFO:               scipy: 1.10.1
2023-09-14 11:08:35,193:INFO:              joblib: 1.3.2
2023-09-14 11:08:35,193:INFO:             sklearn: 1.2.2
2023-09-14 11:08:35,193:INFO:                pyod: 1.1.0
2023-09-14 11:08:35,193:INFO:            imblearn: 0.11.0
2023-09-14 11:08:35,193:INFO:   category_encoders: 2.6.2
2023-09-14 11:08:35,193:INFO:            lightgbm: 4.1.0
2023-09-14 11:08:35,193:INFO:               numba: 0.57.1
2023-09-14 11:08:35,193:INFO:            requests: 2.31.0
2023-09-14 11:08:35,193:INFO:          matplotlib: 3.7.3
2023-09-14 11:08:35,193:INFO:          scikitplot: 0.3.7
2023-09-14 11:08:35,193:INFO:         yellowbrick: 1.5
2023-09-14 11:08:35,193:INFO:              plotly: 5.16.1
2023-09-14 11:08:35,193:INFO:    plotly-resampler: Not installed
2023-09-14 11:08:35,193:INFO:             kaleido: 0.2.1
2023-09-14 11:08:35,194:INFO:           schemdraw: 0.15
2023-09-14 11:08:35,194:INFO:         statsmodels: 0.14.0
2023-09-14 11:08:35,194:INFO:              sktime: 0.21.1
2023-09-14 11:08:35,194:INFO:               tbats: 1.1.3
2023-09-14 11:08:35,194:INFO:            pmdarima: 2.0.3
2023-09-14 11:08:35,194:INFO:              psutil: 5.9.5
2023-09-14 11:08:35,194:INFO:          markupsafe: 2.1.3
2023-09-14 11:08:35,194:INFO:             pickle5: Not installed
2023-09-14 11:08:35,194:INFO:         cloudpickle: 2.2.1
2023-09-14 11:08:35,194:INFO:         deprecation: 2.1.0
2023-09-14 11:08:35,194:INFO:              xxhash: 3.3.0
2023-09-14 11:08:35,194:INFO:           wurlitzer: Not installed
2023-09-14 11:08:35,194:INFO:PyCaret optional dependencies:
2023-09-14 11:08:35,195:INFO:                shap: Not installed
2023-09-14 11:08:35,195:INFO:           interpret: Not installed
2023-09-14 11:08:35,195:INFO:                umap: Not installed
2023-09-14 11:08:35,195:INFO:     ydata_profiling: Not installed
2023-09-14 11:08:35,195:INFO:  explainerdashboard: Not installed
2023-09-14 11:08:35,195:INFO:             autoviz: Not installed
2023-09-14 11:08:35,195:INFO:           fairlearn: Not installed
2023-09-14 11:08:35,195:INFO:          deepchecks: Not installed
2023-09-14 11:08:35,195:INFO:             xgboost: Not installed
2023-09-14 11:08:35,195:INFO:            catboost: Not installed
2023-09-14 11:08:35,195:INFO:              kmodes: Not installed
2023-09-14 11:08:35,195:INFO:             mlxtend: Not installed
2023-09-14 11:08:35,195:INFO:       statsforecast: Not installed
2023-09-14 11:08:35,195:INFO:        tune_sklearn: Not installed
2023-09-14 11:08:35,195:INFO:                 ray: Not installed
2023-09-14 11:08:35,195:INFO:            hyperopt: Not installed
2023-09-14 11:08:35,195:INFO:              optuna: Not installed
2023-09-14 11:08:35,195:INFO:               skopt: Not installed
2023-09-14 11:08:35,195:INFO:              mlflow: Not installed
2023-09-14 11:08:35,195:INFO:              gradio: Not installed
2023-09-14 11:08:35,195:INFO:             fastapi: Not installed
2023-09-14 11:08:35,195:INFO:             uvicorn: Not installed
2023-09-14 11:08:35,195:INFO:              m2cgen: Not installed
2023-09-14 11:08:35,195:INFO:           evidently: Not installed
2023-09-14 11:08:35,195:INFO:               fugue: Not installed
2023-09-14 11:08:35,195:INFO:           streamlit: Not installed
2023-09-14 11:08:35,195:INFO:             prophet: Not installed
2023-09-14 11:08:35,195:INFO:None
2023-09-14 11:08:35,195:INFO:Set up data.
2023-09-14 11:08:35,211:INFO:Set up folding strategy.
2023-09-14 11:08:35,211:INFO:Set up train/test split.
2023-09-14 11:08:35,212:INFO:Set up index.
2023-09-14 11:08:35,212:INFO:Assigning column types.
2023-09-14 11:08:35,212:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-09-14 11:08:35,246:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-14 11:08:35,246:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-14 11:08:35,277:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,277:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,311:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-09-14 11:08:35,312:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-14 11:08:35,329:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,329:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,329:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-09-14 11:08:35,360:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-14 11:08:35,378:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,378:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,395:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-09-14 11:08:35,426:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,426:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,426:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-09-14 11:08:35,463:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,516:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,567:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,568:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,568:INFO:Preparing preprocessing pipeline...
2023-09-14 11:08:35,568:INFO:Set up simple imputation.
2023-09-14 11:08:35,568:INFO:Set up column name cleaning.
2023-09-14 11:08:35,578:INFO:Finished creating preprocessing pipeline.
2023-09-14 11:08:35,578:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\asiae\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['mean radius', 'mean texture',
                                             'mean perimeter', 'mean area',
                                             'mean smoothness',
                                             'mean compactness',
                                             'mean concavity',
                                             'mean concave points',
                                             'mean symmetry',
                                             'mean fractal dimension',
                                             'radius error', 'texture error',
                                             'perimeter e...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-09-14 11:08:35,578:INFO:Creating final display dataframe.
2023-09-14 11:08:35,629:INFO:Setup _display_container:                     Description             Value
0                    Session id                 0
1                        Target               tgt
2                   Target type            Binary
3           Original data shape         (569, 31)
4        Transformed data shape         (569, 31)
5   Transformed train set shape         (455, 31)
6    Transformed test set shape         (114, 31)
7              Numeric features                30
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              fa9e
2023-09-14 11:08:35,689:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,689:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,739:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,740:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-09-14 11:08:35,740:INFO:setup() successfully completed in 0.6s...............
2023-09-14 11:11:01,714:INFO:Initializing compare_models()
2023-09-14 11:11:01,715:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-14 11:11:01,715:INFO:Checking exceptions
2023-09-14 11:11:01,720:INFO:Preparing display monitor
2023-09-14 11:11:01,743:INFO:Initializing Logistic Regression
2023-09-14 11:11:01,743:INFO:Total runtime is 0.0 minutes
2023-09-14 11:11:01,745:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:01,747:INFO:Initializing create_model()
2023-09-14 11:11:01,747:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:01,747:INFO:Checking exceptions
2023-09-14 11:11:01,747:INFO:Importing libraries
2023-09-14 11:11:01,747:INFO:Copying training dataset
2023-09-14 11:11:01,749:INFO:Defining folds
2023-09-14 11:11:01,749:INFO:Declaring metric variables
2023-09-14 11:11:01,752:INFO:Importing untrained model
2023-09-14 11:11:01,755:INFO:Logistic Regression Imported successfully
2023-09-14 11:11:01,759:INFO:Starting cross validation
2023-09-14 11:11:01,760:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:04,178:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,196:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,197:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,200:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,203:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,210:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,261:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,261:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,261:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,261:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:11:04,292:INFO:Calculating mean and std
2023-09-14 11:11:04,294:INFO:Creating metrics dataframe
2023-09-14 11:11:04,298:INFO:Uploading results into container
2023-09-14 11:11:04,298:INFO:Uploading model into container now
2023-09-14 11:11:04,300:INFO:_master_model_container: 1
2023-09-14 11:11:04,300:INFO:_display_container: 2
2023-09-14 11:11:04,300:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-14 11:11:04,300:INFO:create_model() successfully completed......................................
2023-09-14 11:11:04,360:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:04,361:INFO:Creating metrics dataframe
2023-09-14 11:11:04,366:INFO:Initializing K Neighbors Classifier
2023-09-14 11:11:04,366:INFO:Total runtime is 0.04371628761291504 minutes
2023-09-14 11:11:04,372:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:04,372:INFO:Initializing create_model()
2023-09-14 11:11:04,372:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:04,372:INFO:Checking exceptions
2023-09-14 11:11:04,372:INFO:Importing libraries
2023-09-14 11:11:04,372:INFO:Copying training dataset
2023-09-14 11:11:04,373:INFO:Defining folds
2023-09-14 11:11:04,373:INFO:Declaring metric variables
2023-09-14 11:11:04,377:INFO:Importing untrained model
2023-09-14 11:11:04,379:INFO:K Neighbors Classifier Imported successfully
2023-09-14 11:11:04,379:INFO:Starting cross validation
2023-09-14 11:11:04,379:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:05,925:INFO:Calculating mean and std
2023-09-14 11:11:05,927:INFO:Creating metrics dataframe
2023-09-14 11:11:05,933:INFO:Uploading results into container
2023-09-14 11:11:05,934:INFO:Uploading model into container now
2023-09-14 11:11:05,935:INFO:_master_model_container: 2
2023-09-14 11:11:05,935:INFO:_display_container: 2
2023-09-14 11:11:05,935:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-09-14 11:11:05,935:INFO:create_model() successfully completed......................................
2023-09-14 11:11:05,980:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:05,980:INFO:Creating metrics dataframe
2023-09-14 11:11:05,994:INFO:Initializing Naive Bayes
2023-09-14 11:11:05,994:INFO:Total runtime is 0.07084586222966512 minutes
2023-09-14 11:11:05,998:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:05,998:INFO:Initializing create_model()
2023-09-14 11:11:05,998:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:05,998:INFO:Checking exceptions
2023-09-14 11:11:05,998:INFO:Importing libraries
2023-09-14 11:11:05,998:INFO:Copying training dataset
2023-09-14 11:11:05,999:INFO:Defining folds
2023-09-14 11:11:05,999:INFO:Declaring metric variables
2023-09-14 11:11:06,009:INFO:Importing untrained model
2023-09-14 11:11:06,014:INFO:Naive Bayes Imported successfully
2023-09-14 11:11:06,017:INFO:Starting cross validation
2023-09-14 11:11:06,017:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:06,077:INFO:Calculating mean and std
2023-09-14 11:11:06,077:INFO:Creating metrics dataframe
2023-09-14 11:11:06,078:INFO:Uploading results into container
2023-09-14 11:11:06,078:INFO:Uploading model into container now
2023-09-14 11:11:06,078:INFO:_master_model_container: 3
2023-09-14 11:11:06,078:INFO:_display_container: 2
2023-09-14 11:11:06,078:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-09-14 11:11:06,078:INFO:create_model() successfully completed......................................
2023-09-14 11:11:06,125:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:06,125:INFO:Creating metrics dataframe
2023-09-14 11:11:06,130:INFO:Initializing Decision Tree Classifier
2023-09-14 11:11:06,130:INFO:Total runtime is 0.07312005360921224 minutes
2023-09-14 11:11:06,132:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:06,132:INFO:Initializing create_model()
2023-09-14 11:11:06,132:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:06,135:INFO:Checking exceptions
2023-09-14 11:11:06,135:INFO:Importing libraries
2023-09-14 11:11:06,135:INFO:Copying training dataset
2023-09-14 11:11:06,136:INFO:Defining folds
2023-09-14 11:11:06,136:INFO:Declaring metric variables
2023-09-14 11:11:06,136:INFO:Importing untrained model
2023-09-14 11:11:06,141:INFO:Decision Tree Classifier Imported successfully
2023-09-14 11:11:06,145:INFO:Starting cross validation
2023-09-14 11:11:06,148:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:06,196:INFO:Calculating mean and std
2023-09-14 11:11:06,197:INFO:Creating metrics dataframe
2023-09-14 11:11:06,199:INFO:Uploading results into container
2023-09-14 11:11:06,199:INFO:Uploading model into container now
2023-09-14 11:11:06,200:INFO:_master_model_container: 4
2023-09-14 11:11:06,200:INFO:_display_container: 2
2023-09-14 11:11:06,200:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=0, splitter='best')
2023-09-14 11:11:06,200:INFO:create_model() successfully completed......................................
2023-09-14 11:11:06,228:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:06,228:INFO:Creating metrics dataframe
2023-09-14 11:11:06,247:INFO:Initializing SVM - Linear Kernel
2023-09-14 11:11:06,247:INFO:Total runtime is 0.07506737709045411 minutes
2023-09-14 11:11:06,253:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:06,253:INFO:Initializing create_model()
2023-09-14 11:11:06,253:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:06,253:INFO:Checking exceptions
2023-09-14 11:11:06,253:INFO:Importing libraries
2023-09-14 11:11:06,253:INFO:Copying training dataset
2023-09-14 11:11:06,256:INFO:Defining folds
2023-09-14 11:11:06,256:INFO:Declaring metric variables
2023-09-14 11:11:06,256:INFO:Importing untrained model
2023-09-14 11:11:06,261:INFO:SVM - Linear Kernel Imported successfully
2023-09-14 11:11:06,267:INFO:Starting cross validation
2023-09-14 11:11:06,268:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:06,295:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,296:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,298:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,301:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,301:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,303:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,303:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,304:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,304:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,304:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:11:06,343:INFO:Calculating mean and std
2023-09-14 11:11:06,343:INFO:Creating metrics dataframe
2023-09-14 11:11:06,346:INFO:Uploading results into container
2023-09-14 11:11:06,346:INFO:Uploading model into container now
2023-09-14 11:11:06,346:INFO:_master_model_container: 5
2023-09-14 11:11:06,346:INFO:_display_container: 2
2023-09-14 11:11:06,348:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=0, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-09-14 11:11:06,348:INFO:create_model() successfully completed......................................
2023-09-14 11:11:06,379:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:06,379:INFO:Creating metrics dataframe
2023-09-14 11:11:06,398:INFO:Initializing Ridge Classifier
2023-09-14 11:11:06,398:INFO:Total runtime is 0.07757375240325928 minutes
2023-09-14 11:11:06,402:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:06,402:INFO:Initializing create_model()
2023-09-14 11:11:06,402:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:06,402:INFO:Checking exceptions
2023-09-14 11:11:06,402:INFO:Importing libraries
2023-09-14 11:11:06,402:INFO:Copying training dataset
2023-09-14 11:11:06,405:INFO:Defining folds
2023-09-14 11:11:06,405:INFO:Declaring metric variables
2023-09-14 11:11:06,406:INFO:Importing untrained model
2023-09-14 11:11:06,409:INFO:Ridge Classifier Imported successfully
2023-09-14 11:11:06,415:INFO:Starting cross validation
2023-09-14 11:11:06,415:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:06,434:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.05254e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,434:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.1666e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,434:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.73691e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,434:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.09064e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,441:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.74962e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,443:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.21729e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,443:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.13871e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,444:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,446:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.01569e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,447:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,447:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.92802e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.90181e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,449:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:11:06,479:INFO:Calculating mean and std
2023-09-14 11:11:06,480:INFO:Creating metrics dataframe
2023-09-14 11:11:06,482:INFO:Uploading results into container
2023-09-14 11:11:06,482:INFO:Uploading model into container now
2023-09-14 11:11:06,482:INFO:_master_model_container: 6
2023-09-14 11:11:06,482:INFO:_display_container: 2
2023-09-14 11:11:06,483:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=0, solver='auto',
                tol=0.0001)
2023-09-14 11:11:06,483:INFO:create_model() successfully completed......................................
2023-09-14 11:11:06,512:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:06,512:INFO:Creating metrics dataframe
2023-09-14 11:11:06,531:INFO:Initializing Random Forest Classifier
2023-09-14 11:11:06,531:INFO:Total runtime is 0.07979684670766195 minutes
2023-09-14 11:11:06,536:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:06,536:INFO:Initializing create_model()
2023-09-14 11:11:06,536:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:06,536:INFO:Checking exceptions
2023-09-14 11:11:06,536:INFO:Importing libraries
2023-09-14 11:11:06,536:INFO:Copying training dataset
2023-09-14 11:11:06,539:INFO:Defining folds
2023-09-14 11:11:06,539:INFO:Declaring metric variables
2023-09-14 11:11:06,539:INFO:Importing untrained model
2023-09-14 11:11:06,545:INFO:Random Forest Classifier Imported successfully
2023-09-14 11:11:06,551:INFO:Starting cross validation
2023-09-14 11:11:06,551:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:06,866:INFO:Calculating mean and std
2023-09-14 11:11:06,867:INFO:Creating metrics dataframe
2023-09-14 11:11:06,869:INFO:Uploading results into container
2023-09-14 11:11:06,870:INFO:Uploading model into container now
2023-09-14 11:11:06,870:INFO:_master_model_container: 7
2023-09-14 11:11:06,870:INFO:_display_container: 2
2023-09-14 11:11:06,870:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=0, verbose=0, warm_start=False)
2023-09-14 11:11:06,870:INFO:create_model() successfully completed......................................
2023-09-14 11:11:06,915:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:06,915:INFO:Creating metrics dataframe
2023-09-14 11:11:06,923:INFO:Initializing Quadratic Discriminant Analysis
2023-09-14 11:11:06,923:INFO:Total runtime is 0.08632063468297323 minutes
2023-09-14 11:11:06,927:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:06,927:INFO:Initializing create_model()
2023-09-14 11:11:06,927:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:06,927:INFO:Checking exceptions
2023-09-14 11:11:06,927:INFO:Importing libraries
2023-09-14 11:11:06,927:INFO:Copying training dataset
2023-09-14 11:11:06,928:INFO:Defining folds
2023-09-14 11:11:06,928:INFO:Declaring metric variables
2023-09-14 11:11:06,928:INFO:Importing untrained model
2023-09-14 11:11:06,935:INFO:Quadratic Discriminant Analysis Imported successfully
2023-09-14 11:11:06,943:INFO:Starting cross validation
2023-09-14 11:11:06,943:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:06,999:INFO:Calculating mean and std
2023-09-14 11:11:07,000:INFO:Creating metrics dataframe
2023-09-14 11:11:07,002:INFO:Uploading results into container
2023-09-14 11:11:07,002:INFO:Uploading model into container now
2023-09-14 11:11:07,002:INFO:_master_model_container: 8
2023-09-14 11:11:07,002:INFO:_display_container: 2
2023-09-14 11:11:07,002:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-09-14 11:11:07,003:INFO:create_model() successfully completed......................................
2023-09-14 11:11:07,043:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:07,043:INFO:Creating metrics dataframe
2023-09-14 11:11:07,052:INFO:Initializing Ada Boost Classifier
2023-09-14 11:11:07,052:INFO:Total runtime is 0.08847869634628296 minutes
2023-09-14 11:11:07,054:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:07,054:INFO:Initializing create_model()
2023-09-14 11:11:07,054:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:07,054:INFO:Checking exceptions
2023-09-14 11:11:07,054:INFO:Importing libraries
2023-09-14 11:11:07,054:INFO:Copying training dataset
2023-09-14 11:11:07,059:INFO:Defining folds
2023-09-14 11:11:07,059:INFO:Declaring metric variables
2023-09-14 11:11:07,061:INFO:Importing untrained model
2023-09-14 11:11:07,063:INFO:Ada Boost Classifier Imported successfully
2023-09-14 11:11:07,068:INFO:Starting cross validation
2023-09-14 11:11:07,068:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:07,306:INFO:Calculating mean and std
2023-09-14 11:11:07,308:INFO:Creating metrics dataframe
2023-09-14 11:11:07,310:INFO:Uploading results into container
2023-09-14 11:11:07,310:INFO:Uploading model into container now
2023-09-14 11:11:07,311:INFO:_master_model_container: 9
2023-09-14 11:11:07,311:INFO:_display_container: 2
2023-09-14 11:11:07,311:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=0)
2023-09-14 11:11:07,311:INFO:create_model() successfully completed......................................
2023-09-14 11:11:07,364:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:07,364:INFO:Creating metrics dataframe
2023-09-14 11:11:07,364:INFO:Initializing Gradient Boosting Classifier
2023-09-14 11:11:07,364:INFO:Total runtime is 0.09367730617523193 minutes
2023-09-14 11:11:07,373:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:07,376:INFO:Initializing create_model()
2023-09-14 11:11:07,376:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:07,376:INFO:Checking exceptions
2023-09-14 11:11:07,376:INFO:Importing libraries
2023-09-14 11:11:07,376:INFO:Copying training dataset
2023-09-14 11:11:07,379:INFO:Defining folds
2023-09-14 11:11:07,379:INFO:Declaring metric variables
2023-09-14 11:11:07,379:INFO:Importing untrained model
2023-09-14 11:11:07,383:INFO:Gradient Boosting Classifier Imported successfully
2023-09-14 11:11:07,389:INFO:Starting cross validation
2023-09-14 11:11:07,389:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:08,009:INFO:Calculating mean and std
2023-09-14 11:11:08,010:INFO:Creating metrics dataframe
2023-09-14 11:11:08,014:INFO:Uploading results into container
2023-09-14 11:11:08,015:INFO:Uploading model into container now
2023-09-14 11:11:08,015:INFO:_master_model_container: 10
2023-09-14 11:11:08,015:INFO:_display_container: 2
2023-09-14 11:11:08,015:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-14 11:11:08,015:INFO:create_model() successfully completed......................................
2023-09-14 11:11:08,061:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:08,061:INFO:Creating metrics dataframe
2023-09-14 11:11:08,061:INFO:Initializing Linear Discriminant Analysis
2023-09-14 11:11:08,061:INFO:Total runtime is 0.10529370307922363 minutes
2023-09-14 11:11:08,078:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:08,078:INFO:Initializing create_model()
2023-09-14 11:11:08,078:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:08,078:INFO:Checking exceptions
2023-09-14 11:11:08,078:INFO:Importing libraries
2023-09-14 11:11:08,078:INFO:Copying training dataset
2023-09-14 11:11:08,079:INFO:Defining folds
2023-09-14 11:11:08,079:INFO:Declaring metric variables
2023-09-14 11:11:08,079:INFO:Importing untrained model
2023-09-14 11:11:08,086:INFO:Linear Discriminant Analysis Imported successfully
2023-09-14 11:11:08,093:INFO:Starting cross validation
2023-09-14 11:11:08,094:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:08,148:INFO:Calculating mean and std
2023-09-14 11:11:08,149:INFO:Creating metrics dataframe
2023-09-14 11:11:08,151:INFO:Uploading results into container
2023-09-14 11:11:08,151:INFO:Uploading model into container now
2023-09-14 11:11:08,152:INFO:_master_model_container: 11
2023-09-14 11:11:08,152:INFO:_display_container: 2
2023-09-14 11:11:08,152:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-09-14 11:11:08,152:INFO:create_model() successfully completed......................................
2023-09-14 11:11:08,197:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:08,197:INFO:Creating metrics dataframe
2023-09-14 11:11:08,205:INFO:Initializing Extra Trees Classifier
2023-09-14 11:11:08,205:INFO:Total runtime is 0.10769519408543904 minutes
2023-09-14 11:11:08,206:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:08,206:INFO:Initializing create_model()
2023-09-14 11:11:08,209:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:08,209:INFO:Checking exceptions
2023-09-14 11:11:08,209:INFO:Importing libraries
2023-09-14 11:11:08,209:INFO:Copying training dataset
2023-09-14 11:11:08,211:INFO:Defining folds
2023-09-14 11:11:08,211:INFO:Declaring metric variables
2023-09-14 11:11:08,214:INFO:Importing untrained model
2023-09-14 11:11:08,217:INFO:Extra Trees Classifier Imported successfully
2023-09-14 11:11:08,219:INFO:Starting cross validation
2023-09-14 11:11:08,222:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:08,475:INFO:Calculating mean and std
2023-09-14 11:11:08,476:INFO:Creating metrics dataframe
2023-09-14 11:11:08,479:INFO:Uploading results into container
2023-09-14 11:11:08,479:INFO:Uploading model into container now
2023-09-14 11:11:08,480:INFO:_master_model_container: 12
2023-09-14 11:11:08,480:INFO:_display_container: 2
2023-09-14 11:11:08,480:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:11:08,480:INFO:create_model() successfully completed......................................
2023-09-14 11:11:08,536:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:08,536:INFO:Creating metrics dataframe
2023-09-14 11:11:08,548:INFO:Initializing Light Gradient Boosting Machine
2023-09-14 11:11:08,548:INFO:Total runtime is 0.11340900659561157 minutes
2023-09-14 11:11:08,554:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:08,554:INFO:Initializing create_model()
2023-09-14 11:11:08,554:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:08,555:INFO:Checking exceptions
2023-09-14 11:11:08,555:INFO:Importing libraries
2023-09-14 11:11:08,555:INFO:Copying training dataset
2023-09-14 11:11:08,559:INFO:Defining folds
2023-09-14 11:11:08,560:INFO:Declaring metric variables
2023-09-14 11:11:08,563:INFO:Importing untrained model
2023-09-14 11:11:08,563:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-14 11:11:08,570:INFO:Starting cross validation
2023-09-14 11:11:08,570:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:09,169:INFO:Calculating mean and std
2023-09-14 11:11:09,170:INFO:Creating metrics dataframe
2023-09-14 11:11:09,174:INFO:Uploading results into container
2023-09-14 11:11:09,174:INFO:Uploading model into container now
2023-09-14 11:11:09,174:INFO:_master_model_container: 13
2023-09-14 11:11:09,175:INFO:_display_container: 2
2023-09-14 11:11:09,175:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=0, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-09-14 11:11:09,175:INFO:create_model() successfully completed......................................
2023-09-14 11:11:09,227:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:09,227:INFO:Creating metrics dataframe
2023-09-14 11:11:09,243:INFO:Initializing Dummy Classifier
2023-09-14 11:11:09,243:INFO:Total runtime is 0.12500105698903402 minutes
2023-09-14 11:11:09,243:INFO:SubProcess create_model() called ==================================
2023-09-14 11:11:09,243:INFO:Initializing create_model()
2023-09-14 11:11:09,243:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4A9FC8DF0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:09,243:INFO:Checking exceptions
2023-09-14 11:11:09,243:INFO:Importing libraries
2023-09-14 11:11:09,243:INFO:Copying training dataset
2023-09-14 11:11:09,243:INFO:Defining folds
2023-09-14 11:11:09,243:INFO:Declaring metric variables
2023-09-14 11:11:09,243:INFO:Importing untrained model
2023-09-14 11:11:09,258:INFO:Dummy Classifier Imported successfully
2023-09-14 11:11:09,263:INFO:Starting cross validation
2023-09-14 11:11:09,264:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:11:09,313:INFO:Calculating mean and std
2023-09-14 11:11:09,314:INFO:Creating metrics dataframe
2023-09-14 11:11:09,316:INFO:Uploading results into container
2023-09-14 11:11:09,316:INFO:Uploading model into container now
2023-09-14 11:11:09,316:INFO:_master_model_container: 14
2023-09-14 11:11:09,316:INFO:_display_container: 2
2023-09-14 11:11:09,317:INFO:DummyClassifier(constant=None, random_state=0, strategy='prior')
2023-09-14 11:11:09,317:INFO:create_model() successfully completed......................................
2023-09-14 11:11:09,362:INFO:SubProcess create_model() end ==================================
2023-09-14 11:11:09,362:INFO:Creating metrics dataframe
2023-09-14 11:11:09,379:INFO:Initializing create_model()
2023-09-14 11:11:09,379:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:11:09,379:INFO:Checking exceptions
2023-09-14 11:11:09,381:INFO:Importing libraries
2023-09-14 11:11:09,381:INFO:Copying training dataset
2023-09-14 11:11:09,384:INFO:Defining folds
2023-09-14 11:11:09,384:INFO:Declaring metric variables
2023-09-14 11:11:09,384:INFO:Importing untrained model
2023-09-14 11:11:09,384:INFO:Declaring custom model
2023-09-14 11:11:09,385:INFO:Extra Trees Classifier Imported successfully
2023-09-14 11:11:09,386:INFO:Cross validation set to False
2023-09-14 11:11:09,386:INFO:Fitting Model
2023-09-14 11:11:09,493:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:11:09,493:INFO:create_model() successfully completed......................................
2023-09-14 11:11:09,559:INFO:_master_model_container: 14
2023-09-14 11:11:09,559:INFO:_display_container: 2
2023-09-14 11:11:09,559:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:11:09,560:INFO:compare_models() successfully completed......................................
2023-09-14 11:17:13,202:INFO:Initializing predict_model()
2023-09-14 11:17:13,204:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001E4ACE84EE0>)
2023-09-14 11:17:13,204:INFO:Checking exceptions
2023-09-14 11:17:13,204:INFO:Preloading libraries
2023-09-14 11:17:43,922:INFO:Initializing finalize_model()
2023-09-14 11:17:43,923:INFO:finalize_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), fit_kwargs=None, groups=None, model_only=False, experiment_custom_tags=None)
2023-09-14 11:17:43,923:INFO:Finalizing ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:17:43,926:INFO:Initializing create_model()
2023-09-14 11:17:43,926:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), fold=None, round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=False, metrics=None, display=None, model_only=False, return_train_score=False, kwargs={})
2023-09-14 11:17:43,926:INFO:Checking exceptions
2023-09-14 11:17:43,928:INFO:Importing libraries
2023-09-14 11:17:43,928:INFO:Copying training dataset
2023-09-14 11:17:43,928:INFO:Defining folds
2023-09-14 11:17:43,928:INFO:Declaring metric variables
2023-09-14 11:17:43,929:INFO:Importing untrained model
2023-09-14 11:17:43,929:INFO:Declaring custom model
2023-09-14 11:17:43,929:INFO:Extra Trees Classifier Imported successfully
2023-09-14 11:17:43,929:INFO:Cross validation set to False
2023-09-14 11:17:43,929:INFO:Fitting Model
2023-09-14 11:17:44,029:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['mean radius', 'mean texture',
                                             'mean perimeter', 'mean area',
                                             'mean smoothness',
                                             'mean compactness',
                                             'mean concavity',
                                             'mean concave points',
                                             'mean symmetry',
                                             'mean fractal dimension',
                                             'radius error', 'texture error',
                                             'perimeter error', 'area error',
                                             'smoothness error',
                                             'com...
                 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                      class_weight=None, criterion='gini',
                                      max_depth=None, max_features='sqrt',
                                      max_leaf_nodes=None, max_samples=None,
                                      min_impurity_decrease=0.0,
                                      min_samples_leaf=1, min_samples_split=2,
                                      min_weight_fraction_leaf=0.0,
                                      n_estimators=100, n_jobs=-1,
                                      oob_score=False, random_state=0,
                                      verbose=0, warm_start=False))],
         verbose=False)
2023-09-14 11:17:44,029:INFO:create_model() successfully completed......................................
2023-09-14 11:17:44,076:INFO:_master_model_container: 14
2023-09-14 11:17:44,076:INFO:_display_container: 3
2023-09-14 11:17:44,080:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['mean radius', 'mean texture',
                                             'mean perimeter', 'mean area',
                                             'mean smoothness',
                                             'mean compactness',
                                             'mean concavity',
                                             'mean concave points',
                                             'mean symmetry',
                                             'mean fractal dimension',
                                             'radius error', 'texture error',
                                             'perimeter error', 'area error',
                                             'smoothness error',
                                             'com...
                 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                      class_weight=None, criterion='gini',
                                      max_depth=None, max_features='sqrt',
                                      max_leaf_nodes=None, max_samples=None,
                                      min_impurity_decrease=0.0,
                                      min_samples_leaf=1, min_samples_split=2,
                                      min_weight_fraction_leaf=0.0,
                                      n_estimators=100, n_jobs=-1,
                                      oob_score=False, random_state=0,
                                      verbose=0, warm_start=False))],
         verbose=False)
2023-09-14 11:17:44,080:INFO:finalize_model() successfully completed......................................
2023-09-14 11:18:09,671:INFO:Initializing predict_model()
2023-09-14 11:18:09,671:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001E4AD05C790>)
2023-09-14 11:18:09,671:INFO:Checking exceptions
2023-09-14 11:18:09,671:INFO:Preloading libraries
2023-09-14 11:18:09,673:INFO:Set up data.
2023-09-14 11:18:09,683:INFO:Set up index.
2023-09-14 11:18:18,022:INFO:Initializing predict_model()
2023-09-14 11:18:18,023:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001E4AD05C700>)
2023-09-14 11:18:18,023:INFO:Checking exceptions
2023-09-14 11:18:18,023:INFO:Preloading libraries
2023-09-14 11:18:18,025:INFO:Set up data.
2023-09-14 11:18:18,033:INFO:Set up index.
2023-09-14 11:21:24,893:INFO:Initializing predict_model()
2023-09-14 11:21:24,893:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001E4ACE5B640>)
2023-09-14 11:21:24,895:INFO:Checking exceptions
2023-09-14 11:21:24,895:INFO:Preloading libraries
2023-09-14 11:21:24,898:INFO:Set up data.
2023-09-14 11:21:24,903:INFO:Set up index.
2023-09-14 11:43:04,069:INFO:Initializing compare_models()
2023-09-14 11:43:04,069:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-09-14 11:43:04,069:INFO:Checking exceptions
2023-09-14 11:43:04,073:INFO:Preparing display monitor
2023-09-14 11:43:04,096:INFO:Initializing Logistic Regression
2023-09-14 11:43:04,096:INFO:Total runtime is 0.0 minutes
2023-09-14 11:43:04,099:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:04,099:INFO:Initializing create_model()
2023-09-14 11:43:04,099:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:04,099:INFO:Checking exceptions
2023-09-14 11:43:04,102:INFO:Importing libraries
2023-09-14 11:43:04,102:INFO:Copying training dataset
2023-09-14 11:43:04,103:INFO:Defining folds
2023-09-14 11:43:04,103:INFO:Declaring metric variables
2023-09-14 11:43:04,106:INFO:Importing untrained model
2023-09-14 11:43:04,109:INFO:Logistic Regression Imported successfully
2023-09-14 11:43:04,116:INFO:Starting cross validation
2023-09-14 11:43:04,119:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:06,612:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,612:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,612:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,612:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,612:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,629:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,660:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,677:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,677:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,693:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-09-14 11:43:06,724:INFO:Calculating mean and std
2023-09-14 11:43:06,725:INFO:Creating metrics dataframe
2023-09-14 11:43:06,728:INFO:Uploading results into container
2023-09-14 11:43:06,729:INFO:Uploading model into container now
2023-09-14 11:43:06,729:INFO:_master_model_container: 15
2023-09-14 11:43:06,729:INFO:_display_container: 7
2023-09-14 11:43:06,729:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-14 11:43:06,729:INFO:create_model() successfully completed......................................
2023-09-14 11:43:06,777:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:06,777:INFO:Creating metrics dataframe
2023-09-14 11:43:06,777:INFO:Initializing K Neighbors Classifier
2023-09-14 11:43:06,777:INFO:Total runtime is 0.04468785127003987 minutes
2023-09-14 11:43:06,791:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:06,792:INFO:Initializing create_model()
2023-09-14 11:43:06,792:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:06,792:INFO:Checking exceptions
2023-09-14 11:43:06,792:INFO:Importing libraries
2023-09-14 11:43:06,792:INFO:Copying training dataset
2023-09-14 11:43:06,794:INFO:Defining folds
2023-09-14 11:43:06,794:INFO:Declaring metric variables
2023-09-14 11:43:06,794:INFO:Importing untrained model
2023-09-14 11:43:06,799:INFO:K Neighbors Classifier Imported successfully
2023-09-14 11:43:06,804:INFO:Starting cross validation
2023-09-14 11:43:06,806:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:08,355:INFO:Calculating mean and std
2023-09-14 11:43:08,355:INFO:Creating metrics dataframe
2023-09-14 11:43:08,361:INFO:Uploading results into container
2023-09-14 11:43:08,362:INFO:Uploading model into container now
2023-09-14 11:43:08,363:INFO:_master_model_container: 16
2023-09-14 11:43:08,363:INFO:_display_container: 7
2023-09-14 11:43:08,363:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-09-14 11:43:08,363:INFO:create_model() successfully completed......................................
2023-09-14 11:43:08,409:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:08,409:INFO:Creating metrics dataframe
2023-09-14 11:43:08,425:INFO:Initializing Naive Bayes
2023-09-14 11:43:08,425:INFO:Total runtime is 0.07214903434117635 minutes
2023-09-14 11:43:08,425:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:08,425:INFO:Initializing create_model()
2023-09-14 11:43:08,425:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:08,435:INFO:Checking exceptions
2023-09-14 11:43:08,435:INFO:Importing libraries
2023-09-14 11:43:08,435:INFO:Copying training dataset
2023-09-14 11:43:08,438:INFO:Defining folds
2023-09-14 11:43:08,438:INFO:Declaring metric variables
2023-09-14 11:43:08,442:INFO:Importing untrained model
2023-09-14 11:43:08,446:INFO:Naive Bayes Imported successfully
2023-09-14 11:43:08,447:INFO:Starting cross validation
2023-09-14 11:43:08,447:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:08,511:INFO:Calculating mean and std
2023-09-14 11:43:08,512:INFO:Creating metrics dataframe
2023-09-14 11:43:08,518:INFO:Uploading results into container
2023-09-14 11:43:08,518:INFO:Uploading model into container now
2023-09-14 11:43:08,518:INFO:_master_model_container: 17
2023-09-14 11:43:08,518:INFO:_display_container: 7
2023-09-14 11:43:08,518:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-09-14 11:43:08,518:INFO:create_model() successfully completed......................................
2023-09-14 11:43:08,563:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:08,563:INFO:Creating metrics dataframe
2023-09-14 11:43:08,568:INFO:Initializing Decision Tree Classifier
2023-09-14 11:43:08,568:INFO:Total runtime is 0.07453754742940268 minutes
2023-09-14 11:43:08,574:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:08,574:INFO:Initializing create_model()
2023-09-14 11:43:08,574:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:08,574:INFO:Checking exceptions
2023-09-14 11:43:08,574:INFO:Importing libraries
2023-09-14 11:43:08,574:INFO:Copying training dataset
2023-09-14 11:43:08,577:INFO:Defining folds
2023-09-14 11:43:08,577:INFO:Declaring metric variables
2023-09-14 11:43:08,577:INFO:Importing untrained model
2023-09-14 11:43:08,577:INFO:Decision Tree Classifier Imported successfully
2023-09-14 11:43:08,577:INFO:Starting cross validation
2023-09-14 11:43:08,577:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:08,644:INFO:Calculating mean and std
2023-09-14 11:43:08,645:INFO:Creating metrics dataframe
2023-09-14 11:43:08,646:INFO:Uploading results into container
2023-09-14 11:43:08,647:INFO:Uploading model into container now
2023-09-14 11:43:08,647:INFO:_master_model_container: 18
2023-09-14 11:43:08,647:INFO:_display_container: 7
2023-09-14 11:43:08,647:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=0, splitter='best')
2023-09-14 11:43:08,647:INFO:create_model() successfully completed......................................
2023-09-14 11:43:08,690:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:08,690:INFO:Creating metrics dataframe
2023-09-14 11:43:08,695:INFO:Initializing SVM - Linear Kernel
2023-09-14 11:43:08,695:INFO:Total runtime is 0.0766511877377828 minutes
2023-09-14 11:43:08,701:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:08,701:INFO:Initializing create_model()
2023-09-14 11:43:08,702:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:08,702:INFO:Checking exceptions
2023-09-14 11:43:08,702:INFO:Importing libraries
2023-09-14 11:43:08,702:INFO:Copying training dataset
2023-09-14 11:43:08,703:INFO:Defining folds
2023-09-14 11:43:08,703:INFO:Declaring metric variables
2023-09-14 11:43:08,708:INFO:Importing untrained model
2023-09-14 11:43:08,710:INFO:SVM - Linear Kernel Imported successfully
2023-09-14 11:43:08,713:INFO:Starting cross validation
2023-09-14 11:43:08,713:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:08,744:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,745:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,746:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,750:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,750:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,756:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,756:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,756:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,757:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,758:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-09-14 11:43:08,775:INFO:Calculating mean and std
2023-09-14 11:43:08,776:INFO:Creating metrics dataframe
2023-09-14 11:43:08,777:INFO:Uploading results into container
2023-09-14 11:43:08,777:INFO:Uploading model into container now
2023-09-14 11:43:08,777:INFO:_master_model_container: 19
2023-09-14 11:43:08,777:INFO:_display_container: 7
2023-09-14 11:43:08,777:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=0, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-09-14 11:43:08,777:INFO:create_model() successfully completed......................................
2023-09-14 11:43:08,821:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:08,821:INFO:Creating metrics dataframe
2023-09-14 11:43:08,829:INFO:Initializing Ridge Classifier
2023-09-14 11:43:08,829:INFO:Total runtime is 0.07887628873189291 minutes
2023-09-14 11:43:08,829:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:08,832:INFO:Initializing create_model()
2023-09-14 11:43:08,832:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:08,832:INFO:Checking exceptions
2023-09-14 11:43:08,832:INFO:Importing libraries
2023-09-14 11:43:08,832:INFO:Copying training dataset
2023-09-14 11:43:08,834:INFO:Defining folds
2023-09-14 11:43:08,834:INFO:Declaring metric variables
2023-09-14 11:43:08,834:INFO:Importing untrained model
2023-09-14 11:43:08,834:INFO:Ridge Classifier Imported successfully
2023-09-14 11:43:08,846:INFO:Starting cross validation
2023-09-14 11:43:08,847:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:08,866:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.1666e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,869:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.09064e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,869:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.05254e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,869:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.73691e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,869:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.74962e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,869:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.01569e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,869:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.21729e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,876:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,877:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.92802e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,877:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,877:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,878:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=3.90181e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,879:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.13871e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-09-14 11:43:08,881:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,881:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,881:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,882:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,882:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,882:WARNING:c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\asiae\asiae2023\python\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-09-14 11:43:08,895:INFO:Calculating mean and std
2023-09-14 11:43:08,896:INFO:Creating metrics dataframe
2023-09-14 11:43:08,898:INFO:Uploading results into container
2023-09-14 11:43:08,899:INFO:Uploading model into container now
2023-09-14 11:43:08,900:INFO:_master_model_container: 20
2023-09-14 11:43:08,900:INFO:_display_container: 7
2023-09-14 11:43:08,900:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=0, solver='auto',
                tol=0.0001)
2023-09-14 11:43:08,900:INFO:create_model() successfully completed......................................
2023-09-14 11:43:08,941:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:08,942:INFO:Creating metrics dataframe
2023-09-14 11:43:08,944:INFO:Initializing Random Forest Classifier
2023-09-14 11:43:08,944:INFO:Total runtime is 0.08080013593037924 minutes
2023-09-14 11:43:08,944:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:08,944:INFO:Initializing create_model()
2023-09-14 11:43:08,944:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:08,944:INFO:Checking exceptions
2023-09-14 11:43:08,944:INFO:Importing libraries
2023-09-14 11:43:08,944:INFO:Copying training dataset
2023-09-14 11:43:08,944:INFO:Defining folds
2023-09-14 11:43:08,944:INFO:Declaring metric variables
2023-09-14 11:43:08,959:INFO:Importing untrained model
2023-09-14 11:43:08,962:INFO:Random Forest Classifier Imported successfully
2023-09-14 11:43:08,962:INFO:Starting cross validation
2023-09-14 11:43:08,962:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:09,275:INFO:Calculating mean and std
2023-09-14 11:43:09,276:INFO:Creating metrics dataframe
2023-09-14 11:43:09,277:INFO:Uploading results into container
2023-09-14 11:43:09,277:INFO:Uploading model into container now
2023-09-14 11:43:09,277:INFO:_master_model_container: 21
2023-09-14 11:43:09,277:INFO:_display_container: 7
2023-09-14 11:43:09,277:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=0, verbose=0, warm_start=False)
2023-09-14 11:43:09,277:INFO:create_model() successfully completed......................................
2023-09-14 11:43:09,323:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:09,323:INFO:Creating metrics dataframe
2023-09-14 11:43:09,340:INFO:Initializing Quadratic Discriminant Analysis
2023-09-14 11:43:09,340:INFO:Total runtime is 0.08740859031677246 minutes
2023-09-14 11:43:09,344:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:09,344:INFO:Initializing create_model()
2023-09-14 11:43:09,344:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:09,344:INFO:Checking exceptions
2023-09-14 11:43:09,344:INFO:Importing libraries
2023-09-14 11:43:09,344:INFO:Copying training dataset
2023-09-14 11:43:09,348:INFO:Defining folds
2023-09-14 11:43:09,348:INFO:Declaring metric variables
2023-09-14 11:43:09,353:INFO:Importing untrained model
2023-09-14 11:43:09,356:INFO:Quadratic Discriminant Analysis Imported successfully
2023-09-14 11:43:09,363:INFO:Starting cross validation
2023-09-14 11:43:09,366:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:09,430:INFO:Calculating mean and std
2023-09-14 11:43:09,431:INFO:Creating metrics dataframe
2023-09-14 11:43:09,433:INFO:Uploading results into container
2023-09-14 11:43:09,433:INFO:Uploading model into container now
2023-09-14 11:43:09,433:INFO:_master_model_container: 22
2023-09-14 11:43:09,433:INFO:_display_container: 7
2023-09-14 11:43:09,433:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-09-14 11:43:09,433:INFO:create_model() successfully completed......................................
2023-09-14 11:43:09,476:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:09,476:INFO:Creating metrics dataframe
2023-09-14 11:43:09,484:INFO:Initializing Ada Boost Classifier
2023-09-14 11:43:09,484:INFO:Total runtime is 0.08979407946268718 minutes
2023-09-14 11:43:09,487:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:09,487:INFO:Initializing create_model()
2023-09-14 11:43:09,487:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:09,487:INFO:Checking exceptions
2023-09-14 11:43:09,487:INFO:Importing libraries
2023-09-14 11:43:09,487:INFO:Copying training dataset
2023-09-14 11:43:09,490:INFO:Defining folds
2023-09-14 11:43:09,490:INFO:Declaring metric variables
2023-09-14 11:43:09,492:INFO:Importing untrained model
2023-09-14 11:43:09,495:INFO:Ada Boost Classifier Imported successfully
2023-09-14 11:43:09,501:INFO:Starting cross validation
2023-09-14 11:43:09,501:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:09,748:INFO:Calculating mean and std
2023-09-14 11:43:09,757:INFO:Creating metrics dataframe
2023-09-14 11:43:09,760:INFO:Uploading results into container
2023-09-14 11:43:09,760:INFO:Uploading model into container now
2023-09-14 11:43:09,760:INFO:_master_model_container: 23
2023-09-14 11:43:09,760:INFO:_display_container: 7
2023-09-14 11:43:09,764:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=0)
2023-09-14 11:43:09,764:INFO:create_model() successfully completed......................................
2023-09-14 11:43:09,809:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:09,809:INFO:Creating metrics dataframe
2023-09-14 11:43:09,810:INFO:Initializing Gradient Boosting Classifier
2023-09-14 11:43:09,810:INFO:Total runtime is 0.09523164431254069 minutes
2023-09-14 11:43:09,820:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:09,820:INFO:Initializing create_model()
2023-09-14 11:43:09,820:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:09,820:INFO:Checking exceptions
2023-09-14 11:43:09,820:INFO:Importing libraries
2023-09-14 11:43:09,820:INFO:Copying training dataset
2023-09-14 11:43:09,822:INFO:Defining folds
2023-09-14 11:43:09,822:INFO:Declaring metric variables
2023-09-14 11:43:09,825:INFO:Importing untrained model
2023-09-14 11:43:09,828:INFO:Gradient Boosting Classifier Imported successfully
2023-09-14 11:43:09,830:INFO:Starting cross validation
2023-09-14 11:43:09,830:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:10,453:INFO:Calculating mean and std
2023-09-14 11:43:10,453:INFO:Creating metrics dataframe
2023-09-14 11:43:10,460:INFO:Uploading results into container
2023-09-14 11:43:10,460:INFO:Uploading model into container now
2023-09-14 11:43:10,460:INFO:_master_model_container: 24
2023-09-14 11:43:10,460:INFO:_display_container: 7
2023-09-14 11:43:10,460:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-09-14 11:43:10,460:INFO:create_model() successfully completed......................................
2023-09-14 11:43:10,509:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:10,509:INFO:Creating metrics dataframe
2023-09-14 11:43:10,511:INFO:Initializing Linear Discriminant Analysis
2023-09-14 11:43:10,511:INFO:Total runtime is 0.10691294272740683 minutes
2023-09-14 11:43:10,524:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:10,524:INFO:Initializing create_model()
2023-09-14 11:43:10,525:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:10,525:INFO:Checking exceptions
2023-09-14 11:43:10,525:INFO:Importing libraries
2023-09-14 11:43:10,525:INFO:Copying training dataset
2023-09-14 11:43:10,528:INFO:Defining folds
2023-09-14 11:43:10,528:INFO:Declaring metric variables
2023-09-14 11:43:10,529:INFO:Importing untrained model
2023-09-14 11:43:10,529:INFO:Linear Discriminant Analysis Imported successfully
2023-09-14 11:43:10,529:INFO:Starting cross validation
2023-09-14 11:43:10,529:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:10,592:INFO:Calculating mean and std
2023-09-14 11:43:10,593:INFO:Creating metrics dataframe
2023-09-14 11:43:10,595:INFO:Uploading results into container
2023-09-14 11:43:10,595:INFO:Uploading model into container now
2023-09-14 11:43:10,595:INFO:_master_model_container: 25
2023-09-14 11:43:10,595:INFO:_display_container: 7
2023-09-14 11:43:10,595:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-09-14 11:43:10,595:INFO:create_model() successfully completed......................................
2023-09-14 11:43:10,627:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:10,627:INFO:Creating metrics dataframe
2023-09-14 11:43:10,641:INFO:Initializing Extra Trees Classifier
2023-09-14 11:43:10,641:INFO:Total runtime is 0.10909232298533122 minutes
2023-09-14 11:43:10,652:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:10,652:INFO:Initializing create_model()
2023-09-14 11:43:10,652:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:10,652:INFO:Checking exceptions
2023-09-14 11:43:10,652:INFO:Importing libraries
2023-09-14 11:43:10,652:INFO:Copying training dataset
2023-09-14 11:43:10,652:INFO:Defining folds
2023-09-14 11:43:10,652:INFO:Declaring metric variables
2023-09-14 11:43:10,652:INFO:Importing untrained model
2023-09-14 11:43:10,659:INFO:Extra Trees Classifier Imported successfully
2023-09-14 11:43:10,664:INFO:Starting cross validation
2023-09-14 11:43:10,665:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:10,915:INFO:Calculating mean and std
2023-09-14 11:43:10,915:INFO:Creating metrics dataframe
2023-09-14 11:43:10,915:INFO:Uploading results into container
2023-09-14 11:43:10,915:INFO:Uploading model into container now
2023-09-14 11:43:10,915:INFO:_master_model_container: 26
2023-09-14 11:43:10,915:INFO:_display_container: 7
2023-09-14 11:43:10,915:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:43:10,920:INFO:create_model() successfully completed......................................
2023-09-14 11:43:10,967:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:10,967:INFO:Creating metrics dataframe
2023-09-14 11:43:10,975:INFO:Initializing Light Gradient Boosting Machine
2023-09-14 11:43:10,975:INFO:Total runtime is 0.11465313037236533 minutes
2023-09-14 11:43:10,975:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:10,975:INFO:Initializing create_model()
2023-09-14 11:43:10,975:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:10,975:INFO:Checking exceptions
2023-09-14 11:43:10,975:INFO:Importing libraries
2023-09-14 11:43:10,975:INFO:Copying training dataset
2023-09-14 11:43:10,975:INFO:Defining folds
2023-09-14 11:43:10,975:INFO:Declaring metric variables
2023-09-14 11:43:10,975:INFO:Importing untrained model
2023-09-14 11:43:10,975:INFO:Light Gradient Boosting Machine Imported successfully
2023-09-14 11:43:10,975:INFO:Starting cross validation
2023-09-14 11:43:10,990:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:11,522:INFO:Calculating mean and std
2023-09-14 11:43:11,523:INFO:Creating metrics dataframe
2023-09-14 11:43:11,527:INFO:Uploading results into container
2023-09-14 11:43:11,527:INFO:Uploading model into container now
2023-09-14 11:43:11,527:INFO:_master_model_container: 27
2023-09-14 11:43:11,527:INFO:_display_container: 7
2023-09-14 11:43:11,527:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=0, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-09-14 11:43:11,527:INFO:create_model() successfully completed......................................
2023-09-14 11:43:11,575:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:11,575:INFO:Creating metrics dataframe
2023-09-14 11:43:11,598:INFO:Initializing Dummy Classifier
2023-09-14 11:43:11,598:INFO:Total runtime is 0.1250279466311137 minutes
2023-09-14 11:43:11,601:INFO:SubProcess create_model() called ==================================
2023-09-14 11:43:11,601:INFO:Initializing create_model()
2023-09-14 11:43:11,601:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001E4AA24AAA0>, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:11,601:INFO:Checking exceptions
2023-09-14 11:43:11,601:INFO:Importing libraries
2023-09-14 11:43:11,601:INFO:Copying training dataset
2023-09-14 11:43:11,604:INFO:Defining folds
2023-09-14 11:43:11,604:INFO:Declaring metric variables
2023-09-14 11:43:11,606:INFO:Importing untrained model
2023-09-14 11:43:11,609:INFO:Dummy Classifier Imported successfully
2023-09-14 11:43:11,613:INFO:Starting cross validation
2023-09-14 11:43:11,613:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-14 11:43:11,661:INFO:Calculating mean and std
2023-09-14 11:43:11,661:INFO:Creating metrics dataframe
2023-09-14 11:43:11,661:INFO:Uploading results into container
2023-09-14 11:43:11,666:INFO:Uploading model into container now
2023-09-14 11:43:11,666:INFO:_master_model_container: 28
2023-09-14 11:43:11,666:INFO:_display_container: 7
2023-09-14 11:43:11,666:INFO:DummyClassifier(constant=None, random_state=0, strategy='prior')
2023-09-14 11:43:11,666:INFO:create_model() successfully completed......................................
2023-09-14 11:43:11,709:INFO:SubProcess create_model() end ==================================
2023-09-14 11:43:11,709:INFO:Creating metrics dataframe
2023-09-14 11:43:11,742:INFO:Initializing create_model()
2023-09-14 11:43:11,742:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001E4AA4B73D0>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-09-14 11:43:11,742:INFO:Checking exceptions
2023-09-14 11:43:11,744:INFO:Importing libraries
2023-09-14 11:43:11,744:INFO:Copying training dataset
2023-09-14 11:43:11,750:INFO:Defining folds
2023-09-14 11:43:11,750:INFO:Declaring metric variables
2023-09-14 11:43:11,750:INFO:Importing untrained model
2023-09-14 11:43:11,750:INFO:Declaring custom model
2023-09-14 11:43:11,751:INFO:Extra Trees Classifier Imported successfully
2023-09-14 11:43:11,752:INFO:Cross validation set to False
2023-09-14 11:43:11,752:INFO:Fitting Model
2023-09-14 11:43:11,855:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:43:11,856:INFO:create_model() successfully completed......................................
2023-09-14 11:43:11,910:INFO:_master_model_container: 28
2023-09-14 11:43:11,910:INFO:_display_container: 7
2023-09-14 11:43:11,910:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)
2023-09-14 11:43:11,910:INFO:compare_models() successfully completed......................................
